# Form implementation generated from reading ui file '.\scripts\Qt\loading.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoadingDialog(QtWidgets.QDialog):
    def setupUi(self, LoadingDialog):
        LoadingDialog.setObjectName("LoadingDialog")
        LoadingDialog.resize(450, 369)
        LoadingDialog.setMinimumSize(QtCore.QSize(450, 369))
        LoadingDialog.setMaximumSize(QtCore.QSize(450, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(LoadingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loadingLabel = QtWidgets.QLabel(parent=LoadingDialog)
        self.loadingLabel.setStyleSheet("font-size: 18pt; font-weight: bold; color: #555;")
        self.loadingLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loadingLabel.setObjectName("loadingLabel")
        self.verticalLayout.addWidget(self.loadingLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.movieLabel = QtWidgets.QLabel(parent=LoadingDialog)
        self.movieLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.movieLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.movieLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.movieLabel.setObjectName("movieLabel")
        self.horizontalLayout.addWidget(self.movieLabel)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.checkListWidget = QtWidgets.QListWidget(parent=LoadingDialog)
        self.checkListWidget.setStyleSheet(
            "\n"
            "                            QListWidget::item {\n"
            "                            font-size: 14pt;\n"
            "                            color: #333;\n"
            "                            padding: 5px;\n"
            "                            }\n"
            "                            QListWidget::item::checked {\n"
            "                            color: #2A9D8F;\n"
            "                            text-decoration: line-through;\n"
            "                            }\n"
            "                        "
        )
        self.checkListWidget.setObjectName("checkListWidget")
        item = QtWidgets.QListWidgetItem()
        self.checkListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.checkListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.checkListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.checkListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.checkListWidget.addItem(item)
        self.verticalLayout.addWidget(self.checkListWidget)
        self.progressBar = QtWidgets.QProgressBar(parent=LoadingDialog)
        self.progressBar.setStyleSheet(
            "\n"
            "                            QProgressBar {\n"
            "                            border: 1px solid #bbb;\n"
            "                            border-radius: 5px;\n"
            "                            background-color: #eee;\n"
            "                            text-align: center;\n"
            "                            }\n"
            "                            QProgressBar::chunk {\n"
            "                            background-color: #2A9D8F;\n"
            "                            width: 20px;\n"
            "                            }\n"
            "                        "
        )
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(LoadingDialog)
        QtCore.QMetaObject.connectSlotsByName(LoadingDialog)

    def retranslateUi(self, LoadingDialog):
        _translate = QtCore.QCoreApplication.translate
        LoadingDialog.setWindowTitle(_translate("LoadingDialog", "Loading..."))
        LoadingDialog.setStyleSheet(
            _translate(
                "LoadingDialog",
                "\n"
                "                QDialog {\n"
                "                background-color: #ffffff; /* Set the background color to white */\n"
                "                border-radius: 10px;\n"
                "                border: 1px solid #ccc;\n"
                "                }\n"
                "            ",
            )
        )
        self.loadingLabel.setText(_translate("LoadingDialog", "Loading, please wait..."))
        __sortingEnabled = self.checkListWidget.isSortingEnabled()
        self.checkListWidget.setSortingEnabled(False)
        item = self.checkListWidget.item(0)
        item.setText(_translate("LoadingDialog", "Reading sequence data"))
        item = self.checkListWidget.item(1)
        item.setText(_translate("LoadingDialog", "Aligning sequences"))
        item = self.checkListWidget.item(2)
        item.setText(_translate("LoadingDialog", "Constructing genetic trees"))
        item = self.checkListWidget.item(3)
        item.setText(_translate("LoadingDialog", "Displaying results"))
        item = self.checkListWidget.item(4)
        item.setText(_translate("LoadingDialog", "Saving results"))
        self.checkListWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    LoadingDialog = QtWidgets.QDialog()
    ui = Ui_LoadingDialog()
    ui.setupUi(LoadingDialog)
    LoadingDialog.show()
    sys.exit(app.exec())
