# Form implementation generated from reading ui file '.\scripts\Qt\main.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1143, 670)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1143, 670))
        MainWindow.setMaximumSize(QtCore.QSize(1143, 670))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(".\\scripts\\Qt\\../../../../../../hazem/.designer/img/sherbrooke.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off
        )
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.top_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.top_frame.setGeometry(QtCore.QRect(0, -1, 1151, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 221, 218))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 122, 122))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 163, 163))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 221, 218))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 221, 218))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 221, 218))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 122, 122))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 163, 163))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 221, 218))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 221, 218))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 122, 122))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 221, 218))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 122, 122))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 163, 163))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 122, 122))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 122, 122))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 221, 218))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(222, 221, 218))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 245, 244))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        self.top_frame.setPalette(palette)
        self.top_frame.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.top_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.top_frame.setObjectName("top_frame")
        self.helpButton = QtWidgets.QPushButton(parent=self.top_frame)
        self.helpButton.setGeometry(QtCore.QRect(970, 10, 101, 81))
        self.helpButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/other/help.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.helpButton.setIcon(icon1)
        self.helpButton.setIconSize(QtCore.QSize(80, 80))
        self.helpButton.setDefault(False)
        self.helpButton.setFlat(False)
        self.helpButton.setObjectName("helpButton")
        self.climaticDataButton = QtWidgets.QPushButton(parent=self.top_frame)
        self.climaticDataButton.setEnabled(True)
        self.climaticDataButton.setGeometry(QtCore.QRect(630, 10, 101, 81))
        font = QtGui.QFont()
        font.setKerning(True)
        self.climaticDataButton.setFont(font)
        self.climaticDataButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/inactive/climaticData.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.climaticDataButton.setIcon(icon2)
        self.climaticDataButton.setIconSize(QtCore.QSize(75, 75))
        self.climaticDataButton.setCheckable(False)
        self.climaticDataButton.setFlat(False)
        self.climaticDataButton.setObjectName("climaticDataButton")
        self.appLogo = QtWidgets.QLabel(parent=self.top_frame)
        self.appLogo.setGeometry(QtCore.QRect(0, 10, 271, 81))
        self.appLogo.setText("")
        self.appLogo.setPixmap(QtGui.QPixmap(".\\scripts\\Qt\\../../img/other/Logo_decoupe.png"))
        self.appLogo.setScaledContents(True)
        self.appLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.appLogo.setObjectName("appLogo")
        self.geneticDataButton = QtWidgets.QPushButton(parent=self.top_frame)
        self.geneticDataButton.setEnabled(True)
        self.geneticDataButton.setGeometry(QtCore.QRect(460, 10, 101, 81))
        font = QtGui.QFont()
        font.setKerning(True)
        self.geneticDataButton.setFont(font)
        self.geneticDataButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/inactive/genetic.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.geneticDataButton.setIcon(icon3)
        self.geneticDataButton.setIconSize(QtCore.QSize(75, 75))
        self.geneticDataButton.setCheckable(False)
        self.geneticDataButton.setFlat(False)
        self.geneticDataButton.setObjectName("geneticDataButton")
        self.darkModeButton = QtWidgets.QPushButton(parent=self.top_frame)
        self.darkModeButton.setGeometry(QtCore.QRect(1090, 10, 41, 41))
        self.darkModeButton.setStyleSheet(
            "QPushButton {\n"
            "              color: white; /* White text */\n"
            "              border: none;\n"
            "              border-radius: 5px; /* Rounded corners */\n"
            "              padding: 10px 20px; /* Button padding */\n"
            "              font-weight: bold; /* Slightly bold text */\n"
            "              transition: background-color 0.3s ease border-color 0.3s ease;\n"
            "              box-shadow 0.3s ease, transform 0.3s ease; /* Transitions for smooth effects */\n"
            "              }\n"
            "\n"
            "              QPushButton:hover {\n"
            "              background-color: #444; /* Slightly lighter on hover */\n"
            "              border-color: #777; /* Even lighter border on hover */\n"
            "              box-shadow: 0 0 10px 2px rgba(255, 255, 255, 0.3); /* Subtle glow effect */\n"
            "              transform: scale(1.05); /* Slightly increase size on hover */\n"
            "              }\n"
            "\n"
            "              /* Optional: Color Pulsing Animation */\n"
            "              @keyframes pulse {\n"
            "\n"
            "              0% { background-color: #444; }\n"
            "\n"
            "              100% { background-color: #555; }\n"
            "              }\n"
            "\n"
            "              QPushButton:hover {\n"
            "              /* ... other hover styles ... */\n"
            "              animation: pulse 1.5s infinite alternate; /* Adjust speed and behavior if needed */\n"
            "              }\n"
            "            "
        )
        self.darkModeButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/other/dark.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.darkModeButton.setIcon(icon4)
        self.darkModeButton.setIconSize(QtCore.QSize(40, 40))
        self.darkModeButton.setObjectName("darkModeButton")
        self.homeButton = QtWidgets.QPushButton(parent=self.top_frame)
        self.homeButton.setGeometry(QtCore.QRect(290, 10, 101, 81))
        font = QtGui.QFont()
        font.setKerning(True)
        self.homeButton.setFont(font)
        self.homeButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/active/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.homeButton.setIcon(icon5)
        self.homeButton.setIconSize(QtCore.QSize(70, 70))
        self.homeButton.setCheckable(False)
        self.homeButton.setFlat(False)
        self.homeButton.setObjectName("homeButton")
        self.resultsButton = QtWidgets.QPushButton(parent=self.top_frame)
        self.resultsButton.setEnabled(False)
        self.resultsButton.setGeometry(QtCore.QRect(800, 10, 101, 81))
        self.resultsButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/inactive/result.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap(":/active/result.svg"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        icon6.addPixmap(QtGui.QPixmap(".\\scripts\\Qt\\\n" "              :/active/result.svg"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.On)
        self.resultsButton.setIcon(icon6)
        self.resultsButton.setIconSize(QtCore.QSize(60, 60))
        self.resultsButton.setFlat(False)
        self.resultsButton.setObjectName("resultsButton")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 99, 1151, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setObjectName("HomePage")
        self.HomeTab = QtWidgets.QFrame(parent=self.HomePage)
        self.HomeTab.setGeometry(QtCore.QRect(0, 0, 1141, 551))
        self.HomeTab.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.HomeTab.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.HomeTab.setObjectName("HomeTab")
        self.HomeText = QtWidgets.QTextEdit(parent=self.HomeTab)
        self.HomeText.setGeometry(QtCore.QRect(10, 30, 1121, 531))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomeText.sizePolicy().hasHeightForWidth())
        self.HomeText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.HomeText.setFont(font)
        self.HomeText.setReadOnly(True)
        self.HomeText.setObjectName("HomeText")
        self.stackedWidget.addWidget(self.HomePage)
        self.GeneticDataPage = QtWidgets.QWidget()
        self.GeneticDataPage.setObjectName("GeneticDataPage")
        self.GeneticDataSideButtons = QtWidgets.QFrame(parent=self.GeneticDataPage)
        self.GeneticDataSideButtons.setGeometry(QtCore.QRect(10, 0, 191, 541))
        self.GeneticDataSideButtons.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.GeneticDataSideButtons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.GeneticDataSideButtons.setObjectName("GeneticDataSideButtons")
        self.sequenceAlignmentButtonPage1 = QtWidgets.QPushButton(parent=self.GeneticDataSideButtons)
        self.sequenceAlignmentButtonPage1.setEnabled(False)
        self.sequenceAlignmentButtonPage1.setGeometry(QtCore.QRect(0, 120, 181, 81))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/inactive/sequence.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sequenceAlignmentButtonPage1.setIcon(icon7)
        self.sequenceAlignmentButtonPage1.setIconSize(QtCore.QSize(60, 70))
        self.sequenceAlignmentButtonPage1.setFlat(False)
        self.sequenceAlignmentButtonPage1.setObjectName("sequenceAlignmentButtonPage1")
        self.statisticsButtonPage1 = QtWidgets.QPushButton(parent=self.GeneticDataSideButtons)
        self.statisticsButtonPage1.setEnabled(False)
        self.statisticsButtonPage1.setGeometry(QtCore.QRect(0, 230, 181, 81))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/inactive/statistics.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.statisticsButtonPage1.setIcon(icon8)
        self.statisticsButtonPage1.setIconSize(QtCore.QSize(50, 50))
        self.statisticsButtonPage1.setFlat(False)
        self.statisticsButtonPage1.setObjectName("statisticsButtonPage1")
        self.fileBrowserButtonPage1 = QtWidgets.QPushButton(parent=self.GeneticDataSideButtons)
        self.fileBrowserButtonPage1.setGeometry(QtCore.QRect(0, 10, 181, 81))
        font = QtGui.QFont()
        font.setKerning(True)
        self.fileBrowserButtonPage1.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/other/Browse.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.fileBrowserButtonPage1.setIcon(icon9)
        self.fileBrowserButtonPage1.setIconSize(QtCore.QSize(60, 90))
        self.fileBrowserButtonPage1.setCheckable(False)
        self.fileBrowserButtonPage1.setFlat(False)
        self.fileBrowserButtonPage1.setObjectName("fileBrowserButtonPage1")
        self.clearButtonPage1 = QtWidgets.QPushButton(parent=self.GeneticDataSideButtons)
        self.clearButtonPage1.setEnabled(True)
        self.clearButtonPage1.setGeometry(QtCore.QRect(0, 450, 181, 81))
        font = QtGui.QFont()
        font.setKerning(True)
        self.clearButtonPage1.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/other/erase.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clearButtonPage1.setIcon(icon10)
        self.clearButtonPage1.setIconSize(QtCore.QSize(60, 90))
        self.clearButtonPage1.setCheckable(False)
        self.clearButtonPage1.setFlat(False)
        self.clearButtonPage1.setObjectName("clearButtonPage1")
        self.geneticTreeButtonPage1 = QtWidgets.QPushButton(parent=self.GeneticDataSideButtons)
        self.geneticTreeButtonPage1.setEnabled(False)
        self.geneticTreeButtonPage1.setGeometry(QtCore.QRect(0, 340, 181, 81))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/inactive/tree.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.geneticTreeButtonPage1.setIcon(icon11)
        self.geneticTreeButtonPage1.setIconSize(QtCore.QSize(100, 100))
        self.geneticTreeButtonPage1.setFlat(False)
        self.geneticTreeButtonPage1.setObjectName("geneticTreeButtonPage1")
        self.GeneticDataTabs = QtWidgets.QFrame(parent=self.GeneticDataPage)
        self.GeneticDataTabs.setGeometry(QtCore.QRect(200, 0, 941, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GeneticDataTabs.sizePolicy().hasHeightForWidth())
        self.GeneticDataTabs.setSizePolicy(sizePolicy)
        self.GeneticDataTabs.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.GeneticDataTabs.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.GeneticDataTabs.setObjectName("GeneticDataTabs")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.GeneticDataTabs)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 921, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.GenTab1 = QtWidgets.QWidget()
        self.GenTab1.setObjectName("GenTab1")
        self.textEditGenStart = QtWidgets.QTextEdit(parent=self.GenTab1)
        self.textEditGenStart.setGeometry(QtCore.QRect(0, 0, 926, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditGenStart.sizePolicy().hasHeightForWidth())
        self.textEditGenStart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textEditGenStart.setFont(font)
        self.textEditGenStart.setReadOnly(True)
        self.textEditGenStart.setObjectName("textEditGenStart")
        self.tabWidget.addTab(self.GenTab1, "")
        self.GenTab2 = QtWidgets.QWidget()
        self.GenTab2.setObjectName("GenTab2")
        self.textEditFasta = QtWidgets.QTextEdit(parent=self.GenTab2)
        self.textEditFasta.setGeometry(QtCore.QRect(0, 0, 926, 511))
        self.textEditFasta.setObjectName("textEditFasta")
        self.tabWidget.addTab(self.GenTab2, "")
        self.GenTab3 = QtWidgets.QWidget()
        self.GenTab3.setObjectName("GenTab3")
        self.seqAlignLabel = QtWidgets.QLabel(parent=self.GenTab3)
        self.seqAlignLabel.setEnabled(True)
        self.seqAlignLabel.setGeometry(QtCore.QRect(10, 90, 900, 400))
        self.seqAlignLabel.setMinimumSize(QtCore.QSize(900, 400))
        self.seqAlignLabel.setMaximumSize(QtCore.QSize(900, 400))
        self.seqAlignLabel.setText("")
        self.seqAlignLabel.setObjectName("seqAlignLabel")
        self.GenStatsFilters = QtWidgets.QFrame(parent=self.GenTab3)
        self.GenStatsFilters.setGeometry(QtCore.QRect(440, 10, 491, 61))
        self.GenStatsFilters.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.GenStatsFilters.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.GenStatsFilters.setObjectName("GenStatsFilters")
        self.starting_position_spinbox_2 = QtWidgets.QSpinBox(parent=self.GenStatsFilters)
        self.starting_position_spinbox_2.setEnabled(False)
        self.starting_position_spinbox_2.setGeometry(QtCore.QRect(350, 30, 111, 22))
        self.starting_position_spinbox_2.setProperty("value", 1)
        self.starting_position_spinbox_2.setObjectName("starting_position_spinbox_2")
        self.window_size_spinbox_2 = QtWidgets.QSpinBox(parent=self.GenStatsFilters)
        self.window_size_spinbox_2.setEnabled(False)
        self.window_size_spinbox_2.setGeometry(QtCore.QRect(180, 30, 111, 22))
        self.window_size_spinbox_2.setProperty("value", 35)
        self.window_size_spinbox_2.setObjectName("window_size_spinbox_2")
        self.label_3 = QtWidgets.QLabel(parent=self.GenStatsFilters)
        self.label_3.setGeometry(QtCore.QRect(190, 10, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.GenStatsFilters)
        self.label_4.setGeometry(QtCore.QRect(360, 10, 121, 16))
        self.label_4.setObjectName("label_4")
        self.StartSequenceAlignmentButton = QtWidgets.QPushButton(parent=self.GenTab3)
        self.StartSequenceAlignmentButton.setGeometry(QtCore.QRect(380, 20, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setKerning(True)
        self.StartSequenceAlignmentButton.setFont(font)
        self.StartSequenceAlignmentButton.setStyleSheet(
            "QPushButton {\n"
            "                      /* Basic styling */\n"
            "                      background-color: #008331; /* Button color */\n"
            "                      color: white; /* Text color */\n"
            "                      font-size: 14px; /* Font size */\n"
            "                      font-weight: bold; /* Bold text */\n"
            "                      border-radius: 8px; /* Rounded corners */\n"
            "                      padding: 10px 20px; /* Padding */\n"
            "                      border: 2px solid #2980b9; /* Border */\n"
            "                      transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Smooth\n"
            "                      transitions */\n"
            "                      }\n"
            "\n"
            "                      QPushButton:hover {\n"
            "                      /* Hover state styling */\n"
            "                      background-color: #7a9244; /* Darker blue on hover */\n"
            "                      border-color: #1c5980; /* Darker border on hover */\n"
            "                      }\n"
            "\n"
            "                      QPushButton:pressed {\n"
            "                      /* Pressed state styling */\n"
            "                      background-color: #1c5980; /* Even darker blue on press */\n"
            "                      border-color: #145374; /* Darker border on press */\n"
            "                      color: #ecf0f1; /* Lighter text on press */\n"
            "                      }"
        )
        self.StartSequenceAlignmentButton.setIconSize(QtCore.QSize(60, 90))
        self.StartSequenceAlignmentButton.setCheckable(False)
        self.StartSequenceAlignmentButton.setFlat(False)
        self.StartSequenceAlignmentButton.setObjectName("StartSequenceAlignmentButton")
        self.geneticSettingsButton = QtWidgets.QPushButton(parent=self.GenTab3)
        self.geneticSettingsButton.setGeometry(QtCore.QRect(30, 17, 111, 51))
        self.geneticSettingsButton.setStyleSheet(
            "QPushButton {\n"
            "                      /* Basic styling */\n"
            "                      background-color: #3498db; /* Button color */\n"
            "                      color: white; /* Text color */\n"
            "                      font-size: 14px; /* Font size */\n"
            "                      font-weight: bold; /* Bold text */\n"
            "                      border-radius: 8px; /* Rounded corners */\n"
            "                      padding: 10px 20px; /* Padding */\n"
            "                      border: 2px solid #2980b9; /* Border */\n"
            "                      transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Smooth\n"
            "                      transitions */\n"
            "                      }\n"
            "\n"
            "                      QPushButton:hover {\n"
            "                      /* Hover state styling */\n"
            "                      background-color: #2980b9; /* Darker blue on hover */\n"
            "                      border-color: #1c5980; /* Darker border on hover */\n"
            "                      }\n"
            "\n"
            "                      QPushButton:pressed {\n"
            "                      /* Pressed state styling */\n"
            "                      background-color: #1c5980; /* Even darker blue on press */\n"
            "                      border-color: #145374; /* Darker border on press */\n"
            "                      color: #ecf0f1; /* Lighter text on press */\n"
            "                      }"
        )
        self.geneticSettingsButton.setObjectName("geneticSettingsButton")
        self.tabWidget.addTab(self.GenTab3, "")
        self.GenTab4 = QtWidgets.QWidget()
        self.GenTab4.setObjectName("GenTab4")
        self.GenStats = QtWidgets.QFrame(parent=self.GenTab4)
        self.GenStats.setGeometry(QtCore.QRect(0, 0, 921, 511))
        self.GenStats.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.GenStats.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.GenStats.setObjectName("GenStats")
        self.GenStatsFilters1 = QtWidgets.QFrame(parent=self.GenStats)
        self.GenStatsFilters1.setGeometry(QtCore.QRect(440, 20, 481, 61))
        self.GenStatsFilters1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.GenStatsFilters1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.GenStatsFilters1.setObjectName("GenStatsFilters1")
        self.downloadSimilarityButton = QtWidgets.QPushButton(parent=self.GenStatsFilters1)
        self.downloadSimilarityButton.setGeometry(QtCore.QRect(360, 10, 93, 28))
        self.downloadSimilarityButton.setObjectName("downloadSimilarityButton")
        self.startingPositionSimilaritySpinBox = QtWidgets.QSpinBox(parent=self.GenStatsFilters1)
        self.startingPositionSimilaritySpinBox.setGeometry(QtCore.QRect(70, 20, 91, 22))
        self.startingPositionSimilaritySpinBox.setMaximum(9999999)
        self.startingPositionSimilaritySpinBox.setObjectName("startingPositionSimilaritySpinBox")
        self.label_6 = QtWidgets.QLabel(parent=self.GenStatsFilters1)
        self.label_6.setGeometry(QtCore.QRect(70, 0, 111, 16))
        self.label_6.setObjectName("label_6")
        self.referenceComboBox = QtWidgets.QComboBox(parent=self.GenStatsFilters1)
        self.referenceComboBox.setGeometry(QtCore.QRect(210, 20, 73, 22))
        self.referenceComboBox.setObjectName("referenceComboBox")
        self.label_7 = QtWidgets.QLabel(parent=self.GenStatsFilters1)
        self.label_7.setGeometry(QtCore.QRect(210, 0, 111, 16))
        self.label_7.setObjectName("label_7")
        self.GenStatsTitle = QtWidgets.QLabel(parent=self.GenStats)
        self.GenStatsTitle.setGeometry(QtCore.QRect(-100, 0, 541, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.GenStatsTitle.setFont(font)
        self.GenStatsTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.GenStatsTitle.setObjectName("GenStatsTitle")
        self.textEditGenStats_2 = QtWidgets.QLabel(parent=self.GenStats)
        self.textEditGenStats_2.setGeometry(QtCore.QRect(10, 100, 900, 400))
        self.textEditGenStats_2.setMinimumSize(QtCore.QSize(900, 400))
        self.textEditGenStats_2.setMaximumSize(QtCore.QSize(800, 400))
        self.textEditGenStats_2.setText("")
        self.textEditGenStats_2.setObjectName("textEditGenStats_2")
        self.similarityWindowSizeSpinBox = QtWidgets.QSpinBox(parent=self.GenStats)
        self.similarityWindowSizeSpinBox.setGeometry(QtCore.QRect(370, 40, 91, 22))
        self.similarityWindowSizeSpinBox.setMinimum(1)
        self.similarityWindowSizeSpinBox.setMaximum(1000)
        self.similarityWindowSizeSpinBox.setProperty("value", 100)
        self.similarityWindowSizeSpinBox.setObjectName("similarityWindowSizeSpinBox")
        self.label_5 = QtWidgets.QLabel(parent=self.GenStats)
        self.label_5.setGeometry(QtCore.QRect(380, 20, 81, 16))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.GenTab4, "")
        self.GenTab5 = QtWidgets.QWidget()
        self.GenTab5.setObjectName("GenTab5")
        self.GeneticTreeLabel = QtWidgets.QLabel(parent=self.GenTab5)
        self.GeneticTreeLabel.setEnabled(True)
        self.GeneticTreeLabel.setGeometry(QtCore.QRect(0, 60, 921, 450))
        self.GeneticTreeLabel.setMinimumSize(QtCore.QSize(921, 450))
        self.GeneticTreeLabel.setMaximumSize(QtCore.QSize(921, 450))
        self.GeneticTreeLabel.setText("")
        self.GeneticTreeLabel.setObjectName("GeneticTreeLabel")
        self.geneticTreescomboBox = QtWidgets.QComboBox(parent=self.GenTab5)
        self.geneticTreescomboBox.setGeometry(QtCore.QRect(740, 10, 131, 22))
        self.geneticTreescomboBox.setObjectName("geneticTreescomboBox")
        self.downloadGraphButton = QtWidgets.QPushButton(parent=self.GenTab5)
        self.downloadGraphButton.setGeometry(QtCore.QRect(610, 0, 121, 41))
        self.downloadGraphButton.setObjectName("downloadGraphButton")
        self.tabWidget.addTab(self.GenTab5, "")
        self.stackedWidget.addWidget(self.GeneticDataPage)
        self.ClimaticDataPage = QtWidgets.QWidget()
        self.ClimaticDataPage.setObjectName("ClimaticDataPage")
        self.ClimaticDataSideButtons = QtWidgets.QFrame(parent=self.ClimaticDataPage)
        self.ClimaticDataSideButtons.setGeometry(QtCore.QRect(10, 0, 191, 541))
        self.ClimaticDataSideButtons.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ClimaticDataSideButtons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ClimaticDataSideButtons.setObjectName("ClimaticDataSideButtons")
        self.clearButtonPage2 = QtWidgets.QPushButton(parent=self.ClimaticDataSideButtons)
        self.clearButtonPage2.setGeometry(QtCore.QRect(0, 440, 181, 81))
        font = QtGui.QFont()
        font.setKerning(True)
        self.clearButtonPage2.setFont(font)
        self.clearButtonPage2.setIcon(icon10)
        self.clearButtonPage2.setIconSize(QtCore.QSize(60, 90))
        self.clearButtonPage2.setCheckable(False)
        self.clearButtonPage2.setFlat(False)
        self.clearButtonPage2.setObjectName("clearButtonPage2")
        self.climaticTreeButtonPage2 = QtWidgets.QPushButton(parent=self.ClimaticDataSideButtons)
        self.climaticTreeButtonPage2.setEnabled(False)
        self.climaticTreeButtonPage2.setGeometry(QtCore.QRect(0, 300, 181, 81))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/inactive/climatic.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.climaticTreeButtonPage2.setIcon(icon12)
        self.climaticTreeButtonPage2.setIconSize(QtCore.QSize(70, 60))
        self.climaticTreeButtonPage2.setFlat(False)
        self.climaticTreeButtonPage2.setObjectName("climaticTreeButtonPage2")
        self.fileBrowserButtonPage2 = QtWidgets.QPushButton(parent=self.ClimaticDataSideButtons)
        self.fileBrowserButtonPage2.setGeometry(QtCore.QRect(0, 20, 181, 81))
        font = QtGui.QFont()
        font.setKerning(True)
        self.fileBrowserButtonPage2.setFont(font)
        self.fileBrowserButtonPage2.setIcon(icon9)
        self.fileBrowserButtonPage2.setIconSize(QtCore.QSize(60, 90))
        self.fileBrowserButtonPage2.setCheckable(False)
        self.fileBrowserButtonPage2.setFlat(False)
        self.fileBrowserButtonPage2.setObjectName("fileBrowserButtonPage2")
        self.statisticsButtonPage2 = QtWidgets.QPushButton(parent=self.ClimaticDataSideButtons)
        self.statisticsButtonPage2.setEnabled(False)
        self.statisticsButtonPage2.setGeometry(QtCore.QRect(0, 160, 181, 81))
        self.statisticsButtonPage2.setIcon(icon8)
        self.statisticsButtonPage2.setIconSize(QtCore.QSize(50, 50))
        self.statisticsButtonPage2.setFlat(False)
        self.statisticsButtonPage2.setObjectName("statisticsButtonPage2")
        self.ClimaticDataTabs = QtWidgets.QFrame(parent=self.ClimaticDataPage)
        self.ClimaticDataTabs.setGeometry(QtCore.QRect(200, 0, 941, 541))
        self.ClimaticDataTabs.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ClimaticDataTabs.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ClimaticDataTabs.setObjectName("ClimaticDataTabs")
        self.tabWidget2 = QtWidgets.QTabWidget(parent=self.ClimaticDataTabs)
        self.tabWidget2.setGeometry(QtCore.QRect(0, 0, 931, 541))
        self.tabWidget2.setObjectName("tabWidget2")
        self.ClimTab1 = QtWidgets.QWidget()
        self.ClimTab1.setObjectName("ClimTab1")
        self.textEditClimStart = QtWidgets.QTextBrowser(parent=self.ClimTab1)
        self.textEditClimStart.setGeometry(QtCore.QRect(0, 0, 931, 511))
        self.textEditClimStart.setObjectName("textEditClimStart")
        self.tabWidget2.addTab(self.ClimTab1, "")
        self.ClimTab2 = QtWidgets.QWidget()
        self.ClimTab2.setObjectName("ClimTab2")
        self.textEditClimData = QtWidgets.QTextBrowser(parent=self.ClimTab2)
        self.textEditClimData.setGeometry(QtCore.QRect(0, 0, 931, 231))
        self.textEditClimData.setObjectName("textEditClimData")
        self.graphicsViewClimData = QtWidgets.QGraphicsView(parent=self.ClimTab2)
        self.graphicsViewClimData.setGeometry(QtCore.QRect(0, 260, 931, 251))
        self.graphicsViewClimData.setObjectName("graphicsViewClimData")
        self.tabWidget2.addTab(self.ClimTab2, "")
        self.ClimTab4 = QtWidgets.QWidget()
        self.ClimTab4.setObjectName("ClimTab4")
        self.frameClimStats = QtWidgets.QFrame(parent=self.ClimTab4)
        self.frameClimStats.setGeometry(QtCore.QRect(0, 0, 921, 551))
        self.frameClimStats.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frameClimStats.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameClimStats.setObjectName("frameClimStats")
        self.StatisticsTitle = QtWidgets.QLabel(parent=self.frameClimStats)
        self.StatisticsTitle.setGeometry(QtCore.QRect(0, 0, 541, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.StatisticsTitle.setFont(font)
        self.StatisticsTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.StatisticsTitle.setObjectName("StatisticsTitle")
        self.ClimaticChartSettings = QtWidgets.QLabel(parent=self.frameClimStats)
        self.ClimaticChartSettings.setGeometry(QtCore.QRect(30, 90, 340, 391))
        self.ClimaticChartSettings.setMinimumSize(QtCore.QSize(340, 391))
        self.ClimaticChartSettings.setMaximumSize(QtCore.QSize(340, 391))
        self.ClimaticChartSettings.setText("")
        self.ClimaticChartSettings.setObjectName("ClimaticChartSettings")
        self.ClimaticChart_2 = QtWidgets.QLabel(parent=self.frameClimStats)
        self.ClimaticChart_2.setGeometry(QtCore.QRect(390, 10, 520, 500))
        self.ClimaticChart_2.setMinimumSize(QtCore.QSize(520, 500))
        self.ClimaticChart_2.setMaximumSize(QtCore.QSize(520, 500))
        self.ClimaticChart_2.setText("")
        self.ClimaticChart_2.setObjectName("ClimaticChart_2")
        self.ClimaticChartSettingsTitle = QtWidgets.QLabel(parent=self.frameClimStats)
        self.ClimaticChartSettingsTitle.setGeometry(QtCore.QRect(50, 90, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ClimaticChartSettingsTitle.setFont(font)
        self.ClimaticChartSettingsTitle.setWhatsThis("")
        self.ClimaticChartSettingsTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ClimaticChartSettingsTitle.setObjectName("ClimaticChartSettingsTitle")
        self.ClimaticChartSettingsTextAxisX = QtWidgets.QLabel(parent=self.frameClimStats)
        self.ClimaticChartSettingsTextAxisX.setGeometry(QtCore.QRect(120, 150, 161, 31))
        self.ClimaticChartSettingsTextAxisX.setWhatsThis("")
        self.ClimaticChartSettingsTextAxisX.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ClimaticChartSettingsTextAxisX.setObjectName("ClimaticChartSettingsTextAxisX")
        self.ClimaticChartSettingsAxisX = QtWidgets.QComboBox(parent=self.frameClimStats)
        self.ClimaticChartSettingsAxisX.setGeometry(QtCore.QRect(40, 180, 321, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClimaticChartSettingsAxisX.sizePolicy().hasHeightForWidth())
        self.ClimaticChartSettingsAxisX.setSizePolicy(sizePolicy)
        self.ClimaticChartSettingsAxisX.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ClimaticChartSettingsAxisX.setAutoFillBackground(False)
        self.ClimaticChartSettingsAxisX.setEditable(False)
        self.ClimaticChartSettingsAxisX.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.ClimaticChartSettingsAxisX.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToMinimumContentsLengthWithIcon)
        self.ClimaticChartSettingsAxisX.setFrame(True)
        self.ClimaticChartSettingsAxisX.setObjectName("ClimaticChartSettingsAxisX")
        self.ClimaticChartSettingsTextAxisY = QtWidgets.QLabel(parent=self.frameClimStats)
        self.ClimaticChartSettingsTextAxisY.setGeometry(QtCore.QRect(120, 230, 161, 31))
        self.ClimaticChartSettingsTextAxisY.setWhatsThis("")
        self.ClimaticChartSettingsTextAxisY.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ClimaticChartSettingsTextAxisY.setObjectName("ClimaticChartSettingsTextAxisY")
        self.ClimaticChartSettingsAxisY = QtWidgets.QComboBox(parent=self.frameClimStats)
        self.ClimaticChartSettingsAxisY.setGeometry(QtCore.QRect(40, 260, 321, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClimaticChartSettingsAxisY.sizePolicy().hasHeightForWidth())
        self.ClimaticChartSettingsAxisY.setSizePolicy(sizePolicy)
        self.ClimaticChartSettingsAxisY.setEditable(False)
        self.ClimaticChartSettingsAxisY.setFrame(True)
        self.ClimaticChartSettingsAxisY.setObjectName("ClimaticChartSettingsAxisY")
        self.PlotTypesCombobox = QtWidgets.QComboBox(parent=self.frameClimStats)
        self.PlotTypesCombobox.setGeometry(QtCore.QRect(40, 340, 321, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlotTypesCombobox.sizePolicy().hasHeightForWidth())
        self.PlotTypesCombobox.setSizePolicy(sizePolicy)
        self.PlotTypesCombobox.setEditable(False)
        self.PlotTypesCombobox.setFrame(True)
        self.PlotTypesCombobox.setObjectName("PlotTypesCombobox")
        self.PlotTypesCombobox.addItem("")
        self.PlotTypesCombobox.addItem("")
        self.PlotTypesCombobox.addItem("")
        self.PlotTypesCombobox.addItem("")
        self.PlotTypesCombobox.addItem("")
        self.PlotsTypesComboBox = QtWidgets.QLabel(parent=self.frameClimStats)
        self.PlotsTypesComboBox.setGeometry(QtCore.QRect(120, 310, 161, 31))
        self.PlotsTypesComboBox.setWhatsThis("")
        self.PlotsTypesComboBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.PlotsTypesComboBox.setObjectName("PlotsTypesComboBox")
        self.climatePlotDownloadButton = QtWidgets.QPushButton(parent=self.frameClimStats)
        self.climatePlotDownloadButton.setGeometry(QtCore.QRect(150, 410, 93, 28))
        self.climatePlotDownloadButton.setObjectName("climatePlotDownloadButton")
        self.tabWidget2.addTab(self.ClimTab4, "")
        self.ClimTab3 = QtWidgets.QWidget()
        self.ClimTab3.setObjectName("ClimTab3")
        self.frameClimTab3 = QtWidgets.QFrame(parent=self.ClimTab3)
        self.frameClimTab3.setGeometry(QtCore.QRect(0, 0, 931, 511))
        self.frameClimTab3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frameClimTab3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameClimTab3.setObjectName("frameClimTab3")
        self.climaticTreesLabel = QtWidgets.QLabel(parent=self.frameClimTab3)
        self.climaticTreesLabel.setGeometry(QtCore.QRect(4, 65, 911, 441))
        self.climaticTreesLabel.setMinimumSize(QtCore.QSize(911, 441))
        self.climaticTreesLabel.setMaximumSize(QtCore.QSize(911, 441))
        self.climaticTreesLabel.setText("")
        self.climaticTreesLabel.setObjectName("climaticTreesLabel")
        self.climaticTreescomboBox = QtWidgets.QComboBox(parent=self.frameClimTab3)
        self.climaticTreescomboBox.setGeometry(QtCore.QRect(790, 20, 131, 22))
        self.climaticTreescomboBox.setObjectName("climaticTreescomboBox")
        self.downloadGraphButton2 = QtWidgets.QPushButton(parent=self.frameClimTab3)
        self.downloadGraphButton2.setGeometry(QtCore.QRect(650, 10, 121, 41))
        self.downloadGraphButton2.setObjectName("downloadGraphButton2")
        self.preferencesButton = QtWidgets.QPushButton(parent=self.frameClimTab3)
        self.preferencesButton.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.preferencesButton.setObjectName("preferencesButton")
        self.tabWidget2.addTab(self.ClimTab3, "")
        self.stackedWidget.addWidget(self.ClimaticDataPage)
        self.ResultsPage = QtWidgets.QWidget()
        self.ResultsPage.setObjectName("ResultsPage")
        self.ResultsSideButtons = QtWidgets.QFrame(parent=self.ResultsPage)
        self.ResultsSideButtons.setGeometry(QtCore.QRect(10, 0, 191, 541))
        self.ResultsSideButtons.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ResultsSideButtons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ResultsSideButtons.setObjectName("ResultsSideButtons")
        self.settingsButtonPage3 = QtWidgets.QPushButton(parent=self.ResultsSideButtons)
        self.settingsButtonPage3.setGeometry(QtCore.QRect(0, 20, 181, 81))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/inactive/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settingsButtonPage3.setIcon(icon13)
        self.settingsButtonPage3.setIconSize(QtCore.QSize(50, 50))
        self.settingsButtonPage3.setFlat(False)
        self.settingsButtonPage3.setObjectName("settingsButtonPage3")
        self.submitButtonPage3 = QtWidgets.QPushButton(parent=self.ResultsSideButtons)
        self.submitButtonPage3.setGeometry(QtCore.QRect(0, 160, 181, 81))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/inactive/submit.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.submitButtonPage3.setIcon(icon14)
        self.submitButtonPage3.setIconSize(QtCore.QSize(50, 50))
        self.submitButtonPage3.setFlat(False)
        self.submitButtonPage3.setObjectName("submitButtonPage3")
        self.statisticsButtonPage3 = QtWidgets.QPushButton(parent=self.ResultsSideButtons)
        self.statisticsButtonPage3.setGeometry(QtCore.QRect(0, 300, 181, 81))
        self.statisticsButtonPage3.setIcon(icon8)
        self.statisticsButtonPage3.setIconSize(QtCore.QSize(50, 50))
        self.statisticsButtonPage3.setFlat(False)
        self.statisticsButtonPage3.setObjectName("statisticsButtonPage3")
        self.clearButtonPage3 = QtWidgets.QPushButton(parent=self.ResultsSideButtons)
        self.clearButtonPage3.setGeometry(QtCore.QRect(0, 440, 181, 81))
        font = QtGui.QFont()
        font.setKerning(True)
        self.clearButtonPage3.setFont(font)
        self.clearButtonPage3.setIcon(icon10)
        self.clearButtonPage3.setIconSize(QtCore.QSize(60, 90))
        self.clearButtonPage3.setCheckable(False)
        self.clearButtonPage3.setFlat(False)
        self.clearButtonPage3.setObjectName("clearButtonPage3")
        self.ResultsTab = QtWidgets.QFrame(parent=self.ResultsPage)
        self.ResultsTab.setGeometry(QtCore.QRect(200, 0, 931, 541))
        self.ResultsTab.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ResultsTab.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ResultsTab.setObjectName("ResultsTab")
        self.ResultsTitle = QtWidgets.QLabel(parent=self.ResultsTab)
        self.ResultsTitle.setGeometry(QtCore.QRect(0, 0, 931, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ResultsTitle.setFont(font)
        self.ResultsTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ResultsTitle.setObjectName("ResultsTitle")
        self.textEditResults = QtWidgets.QTextBrowser(parent=self.ResultsTab)
        self.textEditResults.setGeometry(QtCore.QRect(0, 60, 931, 461))
        self.textEditResults.setObjectName("textEditResults")
        self.stackedWidget.addWidget(self.ResultsPage)
        self.ResultsStats = QtWidgets.QWidget()
        self.ResultsStats.setObjectName("ResultsStats")
        self.ResultsStatsButtons = QtWidgets.QFrame(parent=self.ResultsStats)
        self.ResultsStatsButtons.setGeometry(QtCore.QRect(0, 0, 201, 551))
        self.ResultsStatsButtons.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ResultsStatsButtons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ResultsStatsButtons.setObjectName("ResultsStatsButtons")
        self.settingsButtonPage4 = QtWidgets.QPushButton(parent=self.ResultsStatsButtons)
        self.settingsButtonPage4.setGeometry(QtCore.QRect(10, 20, 181, 81))
        self.settingsButtonPage4.setIcon(icon13)
        self.settingsButtonPage4.setIconSize(QtCore.QSize(50, 50))
        self.settingsButtonPage4.setFlat(False)
        self.settingsButtonPage4.setObjectName("settingsButtonPage4")
        self.submitButtonPage4 = QtWidgets.QPushButton(parent=self.ResultsStatsButtons)
        self.submitButtonPage4.setGeometry(QtCore.QRect(10, 160, 181, 81))
        self.submitButtonPage4.setIcon(icon14)
        self.submitButtonPage4.setIconSize(QtCore.QSize(50, 50))
        self.submitButtonPage4.setFlat(False)
        self.submitButtonPage4.setObjectName("submitButtonPage4")
        self.statisticsButtonPage4 = QtWidgets.QPushButton(parent=self.ResultsStatsButtons)
        self.statisticsButtonPage4.setGeometry(QtCore.QRect(10, 300, 181, 81))
        self.statisticsButtonPage4.setIcon(icon8)
        self.statisticsButtonPage4.setIconSize(QtCore.QSize(50, 50))
        self.statisticsButtonPage4.setFlat(False)
        self.statisticsButtonPage4.setObjectName("statisticsButtonPage4")
        self.clearButtonPage4 = QtWidgets.QPushButton(parent=self.ResultsStatsButtons)
        self.clearButtonPage4.setGeometry(QtCore.QRect(10, 440, 181, 81))
        font = QtGui.QFont()
        font.setKerning(True)
        self.clearButtonPage4.setFont(font)
        self.clearButtonPage4.setIcon(icon10)
        self.clearButtonPage4.setIconSize(QtCore.QSize(60, 90))
        self.clearButtonPage4.setCheckable(False)
        self.clearButtonPage4.setFlat(False)
        self.clearButtonPage4.setObjectName("clearButtonPage4")
        self.ResultsStatsTab = QtWidgets.QFrame(parent=self.ResultsStats)
        self.ResultsStatsTab.setGeometry(QtCore.QRect(200, 0, 921, 571))
        self.ResultsStatsTab.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ResultsStatsTab.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ResultsStatsTab.setObjectName("ResultsStatsTab")
        self.frameResultsStats = QtWidgets.QFrame(parent=self.ResultsStatsTab)
        self.frameResultsStats.setGeometry(QtCore.QRect(0, 0, 921, 541))
        self.frameResultsStats.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frameResultsStats.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameResultsStats.setObjectName("frameResultsStats")
        self.ResultsStatsFilters = QtWidgets.QFrame(parent=self.frameResultsStats)
        self.ResultsStatsFilters.setGeometry(QtCore.QRect(550, 0, 371, 81))
        self.ResultsStatsFilters.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.ResultsStatsFilters.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ResultsStatsFilters.setObjectName("ResultsStatsFilters")
        self.criteriaComboBox = QtWidgets.QComboBox(parent=self.ResultsStatsFilters)
        self.criteriaComboBox.setGeometry(QtCore.QRect(160, 10, 201, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.criteriaComboBox.sizePolicy().hasHeightForWidth())
        self.criteriaComboBox.setSizePolicy(sizePolicy)
        self.criteriaComboBox.setFrame(True)
        self.criteriaComboBox.setObjectName("criteriaComboBox")
        self.ResultsStatsListTitle = QtWidgets.QLabel(parent=self.ResultsStatsFilters)
        self.ResultsStatsListTitle.setGeometry(QtCore.QRect(0, 10, 161, 31))
        self.ResultsStatsListTitle.setWhatsThis("")
        self.ResultsStatsListTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ResultsStatsListTitle.setObjectName("ResultsStatsListTitle")
        self.phyloTreescomboBox = QtWidgets.QComboBox(parent=self.ResultsStatsFilters)
        self.phyloTreescomboBox.setGeometry(QtCore.QRect(160, 50, 201, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phyloTreescomboBox.sizePolicy().hasHeightForWidth())
        self.phyloTreescomboBox.setSizePolicy(sizePolicy)
        self.phyloTreescomboBox.setFrame(True)
        self.phyloTreescomboBox.setObjectName("phyloTreescomboBox")
        self.ResultsStatsListTitle_2 = QtWidgets.QLabel(parent=self.ResultsStatsFilters)
        self.ResultsStatsListTitle_2.setGeometry(QtCore.QRect(0, 50, 161, 31))
        self.ResultsStatsListTitle_2.setWhatsThis("")
        self.ResultsStatsListTitle_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ResultsStatsListTitle_2.setObjectName("ResultsStatsListTitle_2")
        self.ResultsStatsTitle = QtWidgets.QLabel(parent=self.frameResultsStats)
        self.ResultsStatsTitle.setGeometry(QtCore.QRect(0, 0, 541, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ResultsStatsTitle.setFont(font)
        self.ResultsStatsTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ResultsStatsTitle.setObjectName("ResultsStatsTitle")
        self.PhyloTreeLabel = QtWidgets.QLabel(parent=self.frameResultsStats)
        self.PhyloTreeLabel.setGeometry(QtCore.QRect(0, 80, 921, 450))
        self.PhyloTreeLabel.setMinimumSize(QtCore.QSize(921, 450))
        self.PhyloTreeLabel.setMaximumSize(QtCore.QSize(921, 450))
        self.PhyloTreeLabel.setText("")
        self.PhyloTreeLabel.setObjectName("PhyloTreeLabel")
        self.downloadResultsPlotButton = QtWidgets.QPushButton(parent=self.frameResultsStats)
        self.downloadResultsPlotButton.setGeometry(QtCore.QRect(420, 30, 93, 28))
        self.downloadResultsPlotButton.setObjectName("downloadResultsPlotButton")
        self.stackedWidget.addWidget(self.ResultsStats)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iPhyloGeo"))
        self.helpButton.setToolTip(_translate("MainWindow", "How to use the application"))
        self.climaticDataButton.setToolTip(_translate("MainWindow", "Climatic Data"))
        self.geneticDataButton.setToolTip(_translate("MainWindow", "Genetic Data"))
        self.geneticDataButton.setShortcut(_translate("MainWindow", "Down"))
        self.homeButton.setToolTip(_translate("MainWindow", "Home"))
        self.homeButton.setShortcut(_translate("MainWindow", "Down"))
        self.HomeText.setMarkdown(
            _translate(
                "MainWindow",
                "**Welcome to iPhyloGeo**\n"
                "\n"
                "Thank you for downloading our software.\n"
                "\n"
                "Here is your guide to using ***iPhyloGeo:***\n"
                "\n"
                "You can get help by clicking the Help button in the top right corner. \n"
                "\n"
                "To toggle Dark mode, click the moon-shaped button in the top right corner.\n"
                "\n"
                'You can process two types of data extractions: **"Genetic Data"** and **"Climatic\n'
                'Data"**.\n'
                "\n"
                'You can return to the home menu via the **"Home"** button.\n'
                "\n"
                "Once you've selected the method you want to apply to your data, a side menu\n"
                "with new buttons will appear, \n"
                "\n"
                "allowing you to choose and manipulate the files.\n"
                "\n"
                "Results will be outputted in a CSV file that you can rename and place wherever\n"
                "you want.\n"
                "\n"
                "For more specific information, click the Help button to get details about each\n"
                "algorithm.  \n"
                "\n"
                "**© 2024 iPhyloGeo. All rights reserved.**\n"
                "\n"
                "",
            )
        )
        self.HomeText.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'Segoe UI'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
                '<p align="center" style=" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:20pt; font-weight:700;">Welcome to iPhyloGeo</span></p>\n'
                '<p align="center" style=" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt;">Thank you for downloading our software.</span></p>\n'
                '<p style=" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:16pt;">Here is your guide to using </span><span style=" font-size:16pt; font-weight:700; font-style:italic;">iPhyloGeo:</span></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style=" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:14pt;">You can get help by clicking the Help button in the top right corner. </span></p>\n'
                '<p style=" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:14pt;">To toggle Dark mode, click the moon-shaped button in the top right corner.</span></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style=" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:14pt;">You can process two types of data extractions: </span><span style=" font-size:14pt; font-weight:700; color:#0000ff;">&quot;Genetic Data&quot;</span><span style=" font-size:14pt;"> and </span><span style=" font-size:14pt; font-weight:700; color:#0000ff;">&quot;Climatic Data&quot;</span><span style=" font-size:14pt;">.</span></p>\n'
                '<p style=" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:14pt;">You can return to the home menu via the </span><span style=" font-size:14pt; font-weight:700; color:#0000ff;">&quot;Home&quot;</span><span style=" font-size:14pt;"> button.</span></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style=" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:14pt;">Once you\'ve selected the method you want to apply to your data, a side menu with new buttons will appear, </span></p>\n'
                '<p style=" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:14pt;">allowing you to choose and manipulate the files.</span></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style=" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:14pt;">Results will be outputted in a CSV file that you can rename and place wherever you want.</span></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style=" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:14pt;">For more specific information, click the Help button to get details about each algorithm.  </span></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p align="center" style=" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:12pt; font-weight:700; color:#535353;">© 2024 iPhyloGeo. All rights reserved.</span></p></body></html>',
            )
        )
        self.sequenceAlignmentButtonPage1.setText(_translate("MainWindow", " Alignment"))
        self.statisticsButtonPage1.setText(_translate("MainWindow", " Statistics"))
        self.fileBrowserButtonPage1.setText(_translate("MainWindow", " File Browser"))
        self.clearButtonPage1.setText(_translate("MainWindow", " Clear"))
        self.geneticTreeButtonPage1.setText(_translate("MainWindow", "Genetic Tree"))
        self.textEditGenStart.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><title>Get Started</title><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                '</style></head><body style=" font-family:\'Segoe UI\'; font-size:8pt; font-weight:400; font-style:normal;" bgcolor="#f4f4f4">\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'MS Shell Dlg 2\';">                      </span></p>\n'
                "<h1 align=\"center\" style=\" margin-top:40px; margin-bottom:20px; margin-left:37px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:'Arial','sans-serif'; font-size:xx-large; font-weight:600; color:#0056b3;\">Get Started!</span><span style=\" font-family:'Arial','sans-serif'; font-size:xx-large; font-weight:600; color:#333333;\"> </span><span style=\" font-family:'MS Shell Dlg 2'; font-size:xx-large; font-weight:700;\">                      </span></h1>\n"
                "<p style=\" margin-top:12px; margin-bottom:20px; margin-left:37px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:18px; color:#333333;\">For                      the genetic data extraction, follow these steps to obtain the final                      results:</span><span style=\" font-family:'Arial','sans-serif'; font-size:16px; color:#333333;\"> </span><span style=\" font-family:'MS Shell Dlg 2';\">                      </span></p>\n"
                "<p style=\" margin-top:12px; margin-bottom:20px; margin-left:57px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:18px; color:#333333;\">1.                      Select a </span><span style=\" font-family:'Arial','sans-serif'; font-size:18px; font-weight:600; color:#0056b3;\">.fasta</span><span style=\" font-family:'Arial','sans-serif'; font-size:18px; color:#333333;\">                      file using the File Browser button.</span><span style=\" font-family:'Arial','sans-serif'; font-size:16px; color:#333333;\">                      </span><span style=\" font-family:'MS Shell Dlg 2';\">                      </span></p>\n"
                "<p style=\" margin-top:12px; margin-bottom:20px; margin-left:57px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:18px; color:#333333;\">2.                      Proceed to the sequence alignment using the Sequence                      button.</span><span style=\" font-family:'Arial','sans-serif'; font-size:16px; color:#333333;\"> </span><span style=\" font-family:'MS Shell Dlg 2';\">                      </span></p>\n"
                "<p style=\" margin-top:12px; margin-bottom:20px; margin-left:57px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:18px; color:#333333;\">3.                      Create a genetic tree using the Genetic Tree button.</span><span style=\" font-family:'Arial','sans-serif'; font-size:16px; color:#333333;\"> </span><span style=\" font-family:'MS Shell Dlg 2';\">                      </span></p>\n"
                "<p style=\" margin-top:12px; margin-bottom:20px; margin-left:57px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:18px; color:#333333;\">4.                      Export your results by clicking the Results button.</span><span style=\" font-family:'Arial','sans-serif'; font-size:16px; color:#333333;\"> </span><span style=\" font-family:'MS Shell Dlg 2';\">                      </span></p>\n"
                "<p style=\" margin-top:12px; margin-bottom:20px; margin-left:37px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:18px; font-style:italic; color:#555555;\">For more specific information, click the                      </span><span style=\" font-family:'Arial','sans-serif'; font-size:18px; font-weight:600; font-style:italic; color:#555555;\">Help</span><span style=\" font-family:'Arial','sans-serif'; font-size:18px; font-style:italic; color:#555555;\"> button to get all the details you                      need.</span><span style=\" font-family:'Arial','sans-serif'; font-size:16px; color:#333333;\"> </span><span style=\" font-family:'MS Shell Dlg 2';\">                      </span></p>\n"
                "<p align=\"center\" style=\" margin-top:40px; margin-bottom:0px; margin-left:37px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:14px; color:#888888;\">©                      2024 iPhyloGeo. All rights reserved.</span><span style=\" font-family:'Arial','sans-serif'; font-size:16px; color:#333333;\">                      </span></p></body></html>",
            )
        )
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GenTab1), _translate("MainWindow", "Get Started !"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GenTab2), _translate("MainWindow", "Fasta File"))
        self.label_3.setText(_translate("MainWindow", "Window size"))
        self.label_4.setText(_translate("MainWindow", "Starting position"))
        self.StartSequenceAlignmentButton.setText(_translate("MainWindow", "Start"))
        self.geneticSettingsButton.setText(_translate("MainWindow", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GenTab3), _translate("MainWindow", "Sequence Alignment"))
        self.downloadSimilarityButton.setText(_translate("MainWindow", "Download"))
        self.label_6.setText(_translate("MainWindow", "Starting Position"))
        self.label_7.setText(_translate("MainWindow", "Reference"))
        self.GenStatsTitle.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style="\n'
                '                        font-size:24pt; text-decoration: underline;">Alignment\n'
                "                        Chart</span></p></body></html>",
            )
        )
        self.label_5.setText(_translate("MainWindow", "Window size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GenTab4), _translate("MainWindow", "Species Stats"))
        self.downloadGraphButton.setText(_translate("MainWindow", "Download Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.GenTab5), _translate("MainWindow", "Genetic Tree"))
        self.clearButtonPage2.setText(_translate("MainWindow", " Clear"))
        self.climaticTreeButtonPage2.setText(_translate("MainWindow", " Climatic Tree"))
        self.fileBrowserButtonPage2.setText(_translate("MainWindow", " File Browser"))
        self.statisticsButtonPage2.setText(_translate("MainWindow", " Statistics"))
        self.textEditClimStart.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><title>Get Started</title><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                '</style></head><body style=" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;" bgcolor="#f4f4f4">\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;">                      </span></p>\n'
                "<h1 align=\"center\" style=\" margin-top:40px; margin-bottom:20px; margin-left:37px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%; background-color:#ffffff;\"><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; font-weight:600; color:#0056b3;\">Get Started!</span><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; font-weight:600; color:#333333;\"> </span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:700;\">                      </span></h1>\n"
                "<p style=\" margin-top:12px; margin-bottom:20px; margin-left:37px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; color:#333333;\">For                      the climatic data extraction, follow these steps to obtain the final results:                      </span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">                      </span></p>\n"
                "<p style=\" margin-top:12px; margin-bottom:20px; margin-left:57px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; color:#333333;\">1.                      Select a </span><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; font-weight:600; color:#0056b3;\">.csv</span><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; color:#333333;\"> file                      using the File Browser button. </span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">                      </span></p>\n"
                "<p style=\" margin-top:12px; margin-bottom:20px; margin-left:57px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; color:#333333;\">2.                      Proceed to the climatic tree creation using the Climatic Tree button.                      </span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">                      </span></p>\n"
                "<p style=\" margin-top:12px; margin-bottom:20px; margin-left:57px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; color:#333333;\">3.                      Generate the statistics using the Statistics button. </span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">                      </span></p>\n"
                "<p style=\" margin-top:12px; margin-bottom:20px; margin-left:57px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; color:#333333;\">4.                      Export and visualize your results by clicking the Results button.                      </span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">                      </span></p>\n"
                "<p style=\" margin-top:12px; margin-bottom:20px; margin-left:37px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; font-style:italic; color:#555555;\">For more specific information, click the                      </span><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; font-weight:600; font-style:italic; color:#555555;\">Help</span><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; font-style:italic; color:#555555;\"> button to get all the details you                      need.</span><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; color:#333333;\"> </span><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">                      </span></p>\n"
                "<p align=\"center\" style=\" margin-top:40px; margin-bottom:0px; margin-left:37px; margin-right:37px; -qt-block-indent:0; text-indent:0px; line-height:160%;\"><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; color:#888888;\">©                      2024 iPhyloGeo. All rights reserved.</span><span style=\" font-family:'Arial','sans-serif'; font-size:8pt; color:#333333;\">                      </span></p></body></html>",
            )
        )
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.ClimTab1), _translate("MainWindow", "Get Started !"))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.ClimTab2), _translate("MainWindow", "Climatic Data"))
        self.StatisticsTitle.setText(
            _translate(
                "MainWindow",
                "\n"
                '                        <html><head/><body><p><span style="\n'
                "                        font-size:24pt; text-decoration:\n"
                '                        underline;">Statistics</span></p></body></html>',
            )
        )
        self.ClimaticChartSettingsTitle.setText(_translate("MainWindow", "Generate your Graph"))
        self.ClimaticChartSettingsTextAxisX.setText(_translate("MainWindow", "Insert X axis data"))
        self.ClimaticChartSettingsTextAxisY.setText(_translate("MainWindow", "Insert Y axis data"))
        self.PlotTypesCombobox.setItemText(0, _translate("MainWindow", "Scatter Plot"))
        self.PlotTypesCombobox.setItemText(1, _translate("MainWindow", "Line Plot"))
        self.PlotTypesCombobox.setItemText(2, _translate("MainWindow", "Bar Graph"))
        self.PlotTypesCombobox.setItemText(3, _translate("MainWindow", "Violin Plot"))
        self.PlotTypesCombobox.setItemText(4, _translate("MainWindow", "Pie Plot"))
        self.PlotsTypesComboBox.setText(_translate("MainWindow", "choose Plot Type"))
        self.climatePlotDownloadButton.setText(_translate("MainWindow", "Download"))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.ClimTab4), _translate("MainWindow", "Statistics"))
        self.downloadGraphButton2.setText(_translate("MainWindow", "Download Graph"))
        self.preferencesButton.setText(_translate("MainWindow", "Preferences"))
        self.tabWidget2.setTabText(self.tabWidget2.indexOf(self.ClimTab3), _translate("MainWindow", "Climatic Tree"))
        self.settingsButtonPage3.setText(_translate("MainWindow", " Settings"))
        self.submitButtonPage3.setText(_translate("MainWindow", "Save"))
        self.statisticsButtonPage3.setText(_translate("MainWindow", " Statistics"))
        self.clearButtonPage3.setText(_translate("MainWindow", " Clear"))
        self.ResultsTitle.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style="\n'
                "                  font-size:20pt;\n"
                '                  font-weight:600;">Results</span></p></body></html>',
            )
        )
        self.settingsButtonPage4.setText(_translate("MainWindow", " Settings"))
        self.submitButtonPage4.setText(_translate("MainWindow", "Save"))
        self.statisticsButtonPage4.setText(_translate("MainWindow", " Statistics"))
        self.clearButtonPage4.setText(_translate("MainWindow", " Clear"))
        self.ResultsStatsListTitle.setText(_translate("MainWindow", "Condition"))
        self.ResultsStatsListTitle_2.setText(_translate("MainWindow", "trees"))
        self.ResultsStatsTitle.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style="\n'
                "                    font-size:24pt; text-decoration:\n"
                '                    underline;">Statistics</span></p></body></html>',
            )
        )
        self.downloadResultsPlotButton.setText(_translate("MainWindow", "Download"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
