# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_how_to_use(object):
    def setupUi(self, how_to_use):
        how_to_use.setObjectName("how_to_use")
        #
        how_to_use.resize(1243, 1100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(how_to_use.sizePolicy().hasHeightForWidth())
        how_to_use.setSizePolicy(sizePolicy)
        how_to_use.setMinimumSize(QtCore.QSize(1243, 1100))
        how_to_use.setMaximumSize(QtCore.QSize(1243, 1100))
        #        
        self.centralwidget = QtWidgets.QWidget(how_to_use)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(5, 1, 1235, 1095))
        self.textBrowser.setObjectName("textBrowser")
        how_to_use.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(how_to_use)
        self.statusbar.setObjectName("statusbar")
        how_to_use.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(how_to_use)
        self.toolBar.setObjectName("toolBar")
        how_to_use.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionprint = QtWidgets.QAction(how_to_use)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../proj/icons/blueprint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionprint.setIcon(icon)
        self.actionprint.setObjectName("actionprint")
        self.actionPrint = QtWidgets.QAction(how_to_use)
        self.actionPrint.setObjectName("actionPrint")
        self.toolBar.addAction(self.actionPrint)

        self.retranslateUi(how_to_use)
        QtCore.QMetaObject.connectSlotsByName(how_to_use)

    def retranslateUi(self, how_to_use):
        _translate = QtCore.QCoreApplication.translate
        how_to_use.setWindowTitle(_translate("how_to_use", "How To Use"))
        with open("help.txt", "r") as f:
            help_txt = f.read()
            self.textBrowser.setText(help_txt)

        '''
        self.textBrowser.setHtml(_translate("how_to_use", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Steps to use the application</p></body></html>"))
        '''
        self.toolBar.setWindowTitle(_translate("how_to_use", "toolBar"))
        self.actionprint.setText(_translate("how_to_use", "print"))
        self.actionPrint.setText(_translate("how_to_use", "Print"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    how_to_use = QtWidgets.QMainWindow()
    ui = Ui_how_to_use()
    ui.setupUi(how_to_use)
    how_to_use.show()
    sys.exit(app.exec_())
