import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from aphylogeo.params import Params

sys.path.append('..')


class UiDialog(object):
    selected_index = 0

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(431, 444)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(431, 444))
        Dialog.setMaximumSize(QtCore.QSize(431, 444))
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 408, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setIndent(10)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setIndent(10)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setIndent(10)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setIndent(10)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_window = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_window.setMinimum(0)
        self.spinBox_window.setMaximum(1000)
        self.spinBox_window.setSingleStep(1)
        self.spinBox_window.setProperty("value", Params.window_size)  # userData.get_windowSize()
        self.spinBox_window.setObjectName("spinBox_window")
        self.gridLayout.addWidget(self.spinBox_window, 2, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setCurrentIndex(UiDialog.selected_index)
        self.comboBox.activated.connect(self.comboBoxSelected)
        self.gridLayout.addWidget(self.comboBox, 5, 1, 1, 1)
        self.spinBox_step = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_step.setMinimum(0)
        self.spinBox_step.setMaximum(200)
        self.spinBox_step.setSingleStep(1)
        self.spinBox_step.setProperty("value", Params.window_size)  # userData.get_stepSize()
        self.spinBox_step.setObjectName("spinBox_step")
        self.gridLayout.addWidget(self.spinBox_step, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setIndent(10)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setProperty("value",
                                 Params.dist_threshold)  # userData.get_ls threshold /// metric_threshold?
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 6, 1, 1, 1)
        self.spinBox_bootstrap = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_bootstrap.setMinimum(0)
        self.spinBox_bootstrap.setMaximum(1000)
        self.spinBox_bootstrap.setSingleStep(1)
        self.spinBox_bootstrap.setProperty("value",
                                           Params.bootstrap_threshold)  # userData.get_bootstrapValue()
        self.spinBox_bootstrap.setObjectName("spinBox_bootstrap")
        self.gridLayout.addWidget(self.spinBox_bootstrap, 0, 1, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(160, 400, 120, 30))
        self.cancel_button.setObjectName("cancel_button")
        self.cancel_button.setText("Cancel")
        self.cancel_button.clicked.connect(Dialog.close)
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setGeometry(QtCore.QRect(300, 400, 120, 30))
        self.ok_button.setObjectName("ok_button")
        self.ok_button.clicked.connect(self.saveData)
        self.ok_button.clicked.connect(Dialog.close)

        self.translateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def translateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Parameters"))
        self.groupBox.setTitle(_translate("Dialog", "User Parameters"))
        self.label_5.setText(_translate("Dialog", "Metric threshold"))
        self.label_6.setText(_translate("Dialog", "Metrics "))
        self.label.setText(_translate("Dialog", "Bootstrap value"))
        self.label_3.setText(_translate("Dialog", "Window size"))
        self.comboBox.setItemText(0, _translate("Dialog", "Least square"))
        self.comboBox.setItemText(1, _translate("Dialog", "Robinson and Foulds"))
        self.comboBox.setItemText(2, _translate("Dialog", "Quartic"))
        self.comboBox.setItemText(3, _translate("Dialog", "Bipartition distance"))
        self.label_4.setText(_translate("Dialog", "Step size"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.ok_button.setText(_translate("Dialog", "Ok"))

    def saveData(self):
        window_size = self.spinBox_window.value()
        step_size = self.spinBox_step.value()
        bootstrap_value = self.spinBox_bootstrap.value()
        metric_threshold = self.spinBox.value()
        Params.window_size = (window_size)
        Params.window_size = (step_size)
        Params.window_size = (bootstrap_value)
        Params.window_size = (metric_threshold)

    def comboBoxSelected(self, index):
        if index != 0:
            UiDialog.selected_index = index


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = UiDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
